- name: Configure Nginx on Webserver with TLS
  hosts: webserver
  become: true
  vars:
          key_file: /etc/nginx/ssl/nginx.key
          cert_file: /etc/nginx/ssl/nginx.crt
          conf_file: /etc/nginx/conf.d/default
          server_name: localhost
  tasks:

          - name : Install Nginx
            yum:
                    name: nginx
                    state: latest
          - name: Create directories for TLS Certificates
            file:
                    path: /etc/nginx/ssl
                    state: directory

          - name: Copy TLS Key
            copy:
                    src: files/nginx.key
                    dest: "{{key_file}}"
                    owner: root
                    mode: 0600

          - name: Copy TLS Certification
            copy:
                    src: files/nginx.crt
                    dest: "{{cert_file}}"

          - name : Copy Nginx Config File
            template:
                    src: templates/nginx.conf.j2
                    dest: "{{conf_file}}"
            notify: restart nginx

          - name: Copy index.html
            template:
                    src: templates/index.html.j2
                    dest: /usr/share/nginx/html/index.html

  handlers:
          - name: restart nginx
            service:
                    name: nginx
                    state: restarted




